version: "3"
services:
  localstack:
    container_name: "demo-local-stack"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4572:4572"
    environment:
      - SERVICES:s3,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./scripts/localstack:/docker-entrypoint-initaws.d
